CREATE DATABASE XAYDUNGDECHE
GO
USE XAYDUNGDECHE

-- TAO BANG THEGIOI
CREATE TABLE THEGIOI
(
	THEGIOI_ID INTEGER NOT NULL PRIMARY KEY,
	THEGIOI_NAME NVARCHAR(10) NOT NULL 
);
-- TAO BANG VANMINH
CREATE TABLE VANMINH
(
	VANMINH_ID CHAR(4) NOT NULL PRIMARY KEY,
	VANMINH_NAME NVARCHAR(30) NOT NULL,
	CHIHUY NVARCHAR(30) NOT NULL,
	PHONGTHU INTEGER NOT NULL,
	TANCONG INTEGER NOT NULL,
	XAYDUNG INTEGER NOT NULL,
	HUANLUYEN INTEGER NOT NULL,
	RGB VARCHAR(11) NOT NULL
);
-- TAO BANG THANHPHO
CREATE TABLE THANHPHO
(
	CITY_ID CHAR(7) NOT NULL PRIMARY KEY,
	CITY_NAME VARCHAR(12) NOT NULL,
	THEGIOI_ID INTEGER NOT NULL,
	VANMINH_ID CHAR(4) NOT NULL,
	FOREIGN KEY (THEGIOI_ID) REFERENCES THEGIOI(THEGIOI_ID) ON DELETE CASCADE,
	FOREIGN KEY (VANMINH_ID) REFERENCES VANMINH(VANMINH_ID) ON DELETE CASCADE
);
-- TAO BANG BINHCHUNG
CREATE TABLE BINHCHUNG
(
	BINHCHUNG_ID CHAR(4) NOT NULL PRIMARY KEY,
	BINHCHUNG_NAME NVARCHAR(20) NOT NULL,
	PHONGTHU INTEGER NOT NULL,
	TANCONG INTEGER NOT NULL,
	XAYDUNG INTEGER NOT NULL,
	HUANLUYEN INTEGER NOT NULL
);
-- TAO BANG TAINGUYEN
CREATE TABLE TAINGUYEN
(
	TAINGUYEN_ID CHAR(5) NOT NULL PRIMARY KEY,
	TAINGUYEN_NAME NVARCHAR(15) NOT NULL
);
-- TAO BANG THUOCTINH
CREATE TABLE THUOCTINH
(
	CITY_ID CHAR(7) NOT NULL PRIMARY KEY,
	BC01 INTEGER NOT NULL DEFAULT 0,
	BC02 INTEGER NOT NULL DEFAULT 0,
	BC03 INTEGER NOT NULL DEFAULT 0,
	BC04 INTEGER NOT NULL DEFAULT 0,
	BC05 INTEGER NOT NULL DEFAULT 0,
	BC06 INTEGER NOT NULL DEFAULT 0,
	TN_01 INTEGER NOT NULL DEFAULT 0,
	TN_02 INTEGER NOT NULL DEFAULT 0,
	TN_03 INTEGER NOT NULL DEFAULT 0,
	TN_04 INTEGER NOT NULL DEFAULT 0,
	DIEMKN INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (CITY_ID) REFERENCES THANHPHO(CITY_ID) ON DELETE CASCADE
);
-- TAO BANG PHANLOAI
CREATE TABLE PHANLOAI
(
	"START" INTEGER NOT NULL,
	"END" INTEGER NOT NULL,
	"LEVEL" INTEGER NOT NULL PRIMARY KEY
);
-- TAO BANG NGUOICHOI
CREATE TABLE NGUOICHOI
(
	PLAYER_ID INTEGER NOT NULL PRIMARY KEY,
	CITY_ID CHAR(7) NOT NULL,
	HOVATEN NVARCHAR(50) NOT NULL,
	NICKNAME CHAR(12) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	DATE_REGIS DATE NOT NULL,
	DATE_LAST_LOGOUT DATE NOT NULL,
	TONGSOTRAN INTEGER NOT NULL DEFAULT 0,
	CHISOTHANG INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (CITY_ID) REFERENCES THANHPHO(CITY_ID) ON DELETE CASCADE
);
-- TAO BANG CUAHANG
CREATE TABLE CUAHANG
(
	GOIVP_ID CHAR(5) NOT NULL PRIMARY KEY,
	TAINGUYEN_ID CHAR(5) NOT NULL,
	GOIVP_NAME NVARCHAR(40) NOT NULL,
	SOLUONG INTEGER NOT NULL,
	GIATIEN INTEGER NOT NULL,
	FOREIGN KEY (TAINGUYEN_ID) REFERENCES TAINGUYEN(TAINGUYEN_ID) ON DELETE CASCADE
);
-- TAO BANG GIAODICH
CREATE TABLE GIAODICH
(
	GIAODICH_ID CHAR(5) NOT NULL PRIMARY KEY,
	GOIVP_ID CHAR(5) NOT NULL,
	PLAYER_ID INTEGER NOT NULL,
	NGAYGD DATETIME NOT NULL,
	FOREIGN KEY (GOIVP_ID) REFERENCES CUAHANG(GOIVP_ID) ON DELETE CASCADE,
	FOREIGN KEY (PLAYER_ID) REFERENCES NGUOICHOI(PLAYER_ID) ON DELETE CASCADE
);
-- TAO BANG LIENMINH
CREATE TABLE LIENMINH
(
	THEGIOI_ID INTEGER NOT NULL,
	LIENMINH_ID CHAR(5) NOT NULL PRIMARY KEY,
	LIENMINH_NAME VARCHAR(40) NOT NULL,
	BOSS_ID INTEGER NOT NULL,
	THANHLAP DATE NOT NULL DEFAULT GETDATE(),
	DIEMLIENMINH INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (THEGIOI_ID) REFERENCES THEGIOI(THEGIOI_ID) ON DELETE CASCADE
);
-- TAO BANG THANHVIEN
CREATE TABLE THANHVIEN
(
	LIENMINH_ID CHAR(5) NOT NULL,
	PLAYER_ID INTEGER NOT NULL,
	NGAYTGIA DATE NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (LIENMINH_ID) REFERENCES LIENMINH(LIENMINH_ID) ON DELETE CASCADE,
	FOREIGN KEY (PLAYER_ID) REFERENCES NGUOICHOI(PLAYER_ID),
	PRIMARY KEY (LIENMINH_ID, PLAYER_ID) 
);
-- TAO BANG NHIEMVU
CREATE TABLE NHIEMVU
(
	NHIEMVU_ID CHAR(7) NOT NULL PRIMARY KEY,
	NHIEMVU_NAME NVARCHAR(60) NOT NULL,
	NHIEMVU_ND NVARCHAR(60) NOT NULL,
	NHIEMVU_LEVEL INTEGER NOT NULL,
	NGO INTEGER NOT NULL,
	VANG INTEGER NOT NULL,
	"GO" INTEGER NOT NULL,
	KN INTEGER NOT NULL,
	GEM INTEGER NOT NULL,
	FOREIGN KEY (NHIEMVU_LEVEL) REFERENCES PHANLOAI(LEVEL) ON DELETE CASCADE
);
-- TAO BANG THUCHIEN
CREATE TABLE THUCHIEN
(
	CITY_ID CHAR(7) NOT NULL,
	NHIEMVU_ID CHAR(7) NOT NULL,
	"STATUS" VARCHAR(20) NOT NULL DEFAULT 'PROCESSING',
	FOREIGN KEY (NHIEMVU_ID) REFERENCES NHIEMVU(NHIEMVU_ID) ON DELETE CASCADE,
	FOREIGN KEY (CITY_ID) REFERENCES THANHPHO(CITY_ID) ON DELETE CASCADE,
	PRIMARY KEY (NHIEMVU_ID, CITY_ID)
);
-- TAO BANG DOIDAU
CREATE TABLE DOIDAU
(
	TRANDAU_ID CHAR(8) NOT NULL PRIMARY KEY ,
	PLAYER1_ID INTEGER NOT NULL,
	PLAYER2_ID INTEGER NOT NULL,
	START_TIME DATETIME NOT NULL DEFAULT GETDATE(),
	END_TIME DATETIME NOT NULL,
	DURATION TIME NOT NULL,
	WINNER BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (PLAYER1_ID) REFERENCES NGUOICHOI(PLAYER_ID),
	FOREIGN KEY (PLAYER2_ID) REFERENCES NGUOICHOI(PLAYER_ID)
);
-- TAO BANG CHANGE CHO NGUOICHOI
CREATE TABLE NGUOICHOI_CHANGE
(
	PLAYER_ID INT,
	COTHAYDOI VARCHAR(20),
	OLD_DATA NVARCHAR(30),
	NEW_DATA NVARCHAR(30),
	THOIGIAN DATETIME
);
-- TAO BANG CHANGE CHO THANHPHO
CREATE TABLE THANHPHO_CHANGE
(
	CITY_ID CHAR(7),
	COTTHAYDOI VARCHAR(20),
	OLD_DATA VARCHAR(30),
	NEW_DATA VARCHAR(30),
	THOIGIAN DATETIME
);
-- TAO BANG CHANGE THUOCTINH
CREATE TABLE THUOCTINH_CHANGE
(
	CITY_ID VARCHAR(7),
	COTTHAYDOI VARCHAR(20),
	OLD_DATA INTEGER,
	NEW_DATA INTEGER,
	THOIGIAN DATETIME
);
-- TAO BANG CHANGE THUCHIEN
CREATE TABLE THUCHIEN_CHANGE
(
	CITY_ID CHAR(7),
	COTTHAYDOI VARCHAR(20),
	OLD_DATA VARCHAR(30),
	NEW_DATA VARCHAR(30),
	THOIGIAN DATETIME
);
-- TAO BANG CHANGE GIAODICH
CREATE TABLE GIAODICH_CHANGE
(
	GIAODICH_ID CHAR(5),
	COTTHAYDOI VARCHAR(20),
	OLD_DATA VARCHAR(30),
	NEW_DATA VARCHAR(30),
	THOIGIAN DATETIME
);
