-- TRIGGER 7
CREATE TRIGGER THANHPHO_AUDIT
ON THANHPHO
AFTER UPDATE, INSERT
AS
DECLARE @new_CITY_ID AS CHAR(7)
DECLARE @new_CITY_NAME AS CHAR(12)
DECLARE @new_THEGIOI_ID AS INT
DECLARE @new_VANMINH_ID AS CHAR(4)

DECLARE @old_CITY_ID AS CHAR(7)
DECLARE @old_CITY_NAME AS CHAR(12)
DECLARE @old_THEGIOI_ID AS INT
DECLARE @old_VANMINH_ID AS CHAR(4)

SELECT @new_CITY_ID = I.CITY_ID FROM INSERTED AS I
SELECT @new_CITY_NAME = I.CITY_NAME FROM INSERTED AS I
SELECT @new_THEGIOI_ID = I.THEGIOI_ID FROM INSERTED AS I
SELECT @new_VANMINH_ID = I.VANMINH_ID FROM INSERTED AS I

SELECT @old_CITY_ID = I.CITY_ID FROM DELETED AS I
SELECT @old_CITY_NAME = I.CITY_NAME FROM DELETED AS I
SELECT @old_THEGIOI_ID = I.THEGIOI_ID FROM DELETED AS I
SELECT @old_VANMINH_ID = I.VANMINH_ID FROM DELETED AS I

BEGIN
IF @new_CITY_ID <> @old_CITY_ID OR (@old_CITY_ID IS NULL AND @new_CITY_ID IS NOT NULL) OR (@new_CITY_ID IS NULL AND @old_CITY_ID IS NOT NULL)
INSERT INTO THANHPHO_CHANGE VALUES (@new_CITY_ID, 'CITY_ID', @old_CITY_ID, @new_CITY_ID, SYSDATETIME())

IF @new_CITY_NAME <> @old_CITY_NAME OR (@old_CITY_NAME IS NULL AND @new_CITY_NAME IS NOT NULL) OR (@new_CITY_NAME IS NULL AND @old_CITY_NAME IS NOT NULL)
INSERT INTO THANHPHO_CHANGE VALUES (@new_CITY_ID, 'CITY_NAME', @old_CITY_NAME, @new_CITY_NAME, SYSDATETIME())

IF @new_THEGIOI_ID <> @old_THEGIOI_ID OR (@old_THEGIOI_ID IS NULL AND @new_THEGIOI_ID IS NOT NULL) OR (@new_THEGIOI_ID IS NULL AND @old_THEGIOI_ID IS NOT NULL)
INSERT INTO THANHPHO_CHANGE VALUES (@new_CITY_ID, 'THEGIOI_ID', CAST(@old_THEGIOI_ID AS VARCHAR(5)), CAST(@new_THEGIOI_ID AS VARCHAR(5)), SYSDATETIME())

IF @new_VANMINH_ID <> @old_VANMINH_ID OR (@old_VANMINH_ID IS NULL AND @new_VANMINH_ID IS NOT NULL) OR (@new_VANMINH_ID IS NULL AND @old_VANMINH_ID IS NOT NULL)
INSERT INTO THANHPHO_CHANGE VALUES (@new_CITY_ID, 'VANMINH_ID', @old_VANMINH_ID, @new_VANMINH_ID, SYSDATETIME())
END

-- THU KET QUA TRIGGER
UPDATE THANHPHO
SET VANMINH_ID = 'AC01'
WHERE CITY_ID = 'AC42283'

UPDATE THANHPHO
SET CITY_NAME = 'acondinay'
WHERE CITY_ID = 'AC42283'

INSERT INTO THANHPHO
	(CITY_ID, CITY_NAME, THEGIOI_ID, VANMINH_ID) VALUES
		('AK43258', 'conchongu', 2, 'AC01')

SELECT * FROM THANHPHO
SELECT * FROM THANHPHO_CHANGE