-- TRIGGER 1
CREATE TRIGGER HOANTHANHNHIEMVU
ON THUCHIEN
AFTER UPDATE, INSERT
AS
BEGIN
	DECLARE @ketqua VARCHAR(20)
	SELECT @ketqua = I."STATUS" FROM INSERTED AS I

	IF @ketqua = 'DONE'
	BEGIN
		UPDATE THUOCTINH
		SET TN_01 = TN_01 + NHIEMVU.NGO
		FROM inserted, THUCHIEN JOIN NHIEMVU
		ON NHIEMVU.NHIEMVU_ID = THUCHIEN.NHIEMVU_ID
		WHERE INSERTED.CITY_ID = THUOCTINH.CITY_ID

		UPDATE THUOCTINH
		SET TN_02 = TN_02 + NHIEMVU."GO"
		FROM inserted, THUCHIEN JOIN NHIEMVU
		ON NHIEMVU.NHIEMVU_ID = THUCHIEN.NHIEMVU_ID
		WHERE INSERTED.CITY_ID = THUOCTINH.CITY_ID

		UPDATE THUOCTINH
		SET TN_03 = TN_03 + NHIEMVU.VANG
		FROM inserted, THUCHIEN JOIN NHIEMVU
		ON NHIEMVU.NHIEMVU_ID = THUCHIEN.NHIEMVU_ID
		WHERE INSERTED.CITY_ID = THUOCTINH.CITY_ID

		UPDATE THUOCTINH
		SET TN_04 = TN_04 + NHIEMVU.GEM
		FROM inserted, THUCHIEN JOIN NHIEMVU
		ON NHIEMVU.NHIEMVU_ID = THUCHIEN.NHIEMVU_ID
		WHERE INSERTED.CITY_ID = THUOCTINH.CITY_ID

		UPDATE THUOCTINH
		SET DIEMKN = DIEMKN + NHIEMVU.KN
		FROM inserted, THUCHIEN JOIN NHIEMVU
		ON NHIEMVU.NHIEMVU_ID = THUCHIEN.NHIEMVU_ID
		WHERE INSERTED.CITY_ID = THUOCTINH.CITY_ID
	END
END

-- THU KET QUA TRIGGER
UPDATE THUCHIEN
SET STATUS = 'DONE'
WHERE CITY_ID = 'BA37322'

SELECT * FROM THUCHIEN
SELECT * FROM NHIEMVU
SELECT * FROM TAINGUYEN
SELECT * FROM THUOCTINH

