-- TRIGGER 9
CREATE TRIGGER THUCHIEN_AUDIT
ON THUCHIEN
AFTER UPDATE, INSERT
AS
DECLARE @new_CITY_ID AS CHAR(7)
DECLARE @new_NHIEMVU_ID VARCHAR(7)
DECLARE @new_STATUS AS VARCHAR(30)

DECLARE @old_CITY_ID AS CHAR(7)
DECLARE @old_NHIEMVU_ID VARCHAR(7)
DECLARE @old_STATUS AS VARCHAR(30)

SELECT @new_CITY_ID = I.CITY_ID FROM INSERTED AS I
SELECT @new_NHIEMVU_ID = I.NHIEMVU_ID FROM INSERTED AS I
SELECT @new_STATUS = I."STATUS" FROM INSERTED AS I

SELECT @old_CITY_ID = I.CITY_ID FROM DELETED AS I
SELECT @old_NHIEMVU_ID = I.NHIEMVU_ID FROM DELETED AS I
SELECT @old_STATUS = I."STATUS" FROM DELETED AS I

BEGIN
IF @new_CITY_ID <> @old_CITY_ID OR (@old_CITY_ID IS NULL AND @new_CITY_ID IS NOT NULL) OR (@new_CITY_ID IS NULL AND @old_CITY_ID IS NOT NULL)
INSERT INTO THUCHIEN_CHANGE VALUES (@new_CITY_ID, 'CITY_ID', @old_CITY_ID, @new_CITY_ID, SYSDATETIME())

IF @new_NHIEMVU_ID <> @old_NHIEMVU_ID OR (@old_NHIEMVU_ID IS NULL AND @new_NHIEMVU_ID IS NOT NULL) OR (@new_NHIEMVU_ID IS NULL AND @old_NHIEMVU_ID IS NOT NULL)
INSERT INTO THUCHIEN_CHANGE VALUES (@new_CITY_ID, 'NHIEMVU_ID', @old_NHIEMVU_ID, @new_NHIEMVU_ID, SYSDATETIME())

IF @new_STATUS <> @old_STATUS OR (@old_STATUS IS NULL AND @new_STATUS IS NOT NULL) OR (@new_STATUS IS NULL AND @old_STATUS IS NOT NULL)
INSERT INTO THUCHIEN_CHANGE VALUES (@new_CITY_ID, 'STATUS', @old_STATUS, @new_STATUS, SYSDATETIME())
END

-- THU KET QUA TRIGGER
UPDATE THUCHIEN
SET "STATUS" = 'PROCESSING'
WHERE CITY_ID = 'BA37322'
AND NHIEMVU_ID = 'LV101' 

UPDATE THUCHIEN
SET "STATUS" = 'PROCESSING'
WHERE CITY_ID = 'BA37322'
AND (NHIEMVU_ID = 'LV102' OR NHIEMVU_ID = 'LV103')

INSERT INTO THUCHIEN
	(CITY_ID, NHIEMVU_ID) VALUES
	('HA67471', 'LV201')

SELECT * FROM THUCHIEN
SELECT * FROM THUCHIEN_CHANGE