-- TRIGGER 8
CREATE TRIGGER THUOCTINH_AUDIT
ON THUOCTINH
AFTER UPDATE, INSERT
AS
DECLARE @new_CITY_ID AS CHAR(7)
DECLARE @new_BC01 AS INT
DECLARE @new_BC02 AS INT
DECLARE @new_BC03 AS INT
DECLARE @new_BC04 AS INT
DECLARE @new_BC05 AS INT
DECLARE @new_BC06 AS INT
DECLARE @new_TN_01 AS INT
DECLARE @new_TN_02 AS INT
DECLARE @new_TN_03 AS INT
DECLARE @new_TN_04 AS INT
DECLARE @new_DIEMKN AS INT

DECLARE @old_CITY_ID AS CHAR(7)
DECLARE @old_BC01 AS INT
DECLARE @old_BC02 AS INT
DECLARE @old_BC03 AS INT
DECLARE @old_BC04 AS INT
DECLARE @old_BC05 AS INT
DECLARE @old_BC06 AS INT
DECLARE @old_TN_01 AS INT
DECLARE @old_TN_02 AS INT
DECLARE @old_TN_03 AS INT
DECLARE @old_TN_04 AS INT
DECLARE @old_DIEMKN AS INT

SELECT @new_CITY_ID = I.CITY_ID FROM INSERTED AS I
SELECT @new_BC01 = I.BC01 FROM INSERTED AS I
SELECT @new_BC02 = I.BC02 FROM INSERTED AS I
SELECT @new_BC03 = I.BC03 FROM INSERTED AS I
SELECT @new_BC04 = I.BC04 FROM INSERTED AS I
SELECT @new_BC05 = I.BC05 FROM INSERTED AS I
SELECT @new_BC06 = I.BC06 FROM INSERTED AS I
SELECT @new_TN_01 = I.TN_01 FROM INSERTED AS I
SELECT @new_TN_02 = I.TN_02 FROM INSERTED AS I
SELECT @new_TN_03 = I.TN_03 FROM INSERTED AS I
SELECT @new_TN_04 = I.TN_04 FROM INSERTED AS I
SELECT @new_DIEMKN = I.DIEMKN FROM INSERTED AS I

SELECT @old_CITY_ID = I.CITY_ID FROM DELETED AS I
SELECT @old_BC01 = I.BC01 FROM DELETED AS I
SELECT @old_BC02 = I.BC02 FROM DELETED AS I
SELECT @old_BC03 = I.BC03 FROM DELETED AS I
SELECT @old_BC04 = I.BC04 FROM DELETED AS I
SELECT @old_BC05 = I.BC05 FROM DELETED AS I
SELECT @old_BC06 = I.BC06 FROM DELETED AS I
SELECT @old_TN_01 = I.TN_01 FROM DELETED AS I
SELECT @old_TN_02 = I.TN_02 FROM DELETED AS I
SELECT @old_TN_03 = I.TN_03 FROM DELETED AS I
SELECT @old_TN_04 = I.TN_04 FROM DELETED AS I
SELECT @old_DIEMKN = I.DIEMKN FROM DELETED AS I

BEGIN
IF @new_BC01 <> @old_BC01 OR (@old_BC01 IS NULL AND @new_BC01 IS NOT NULL) OR (@new_BC01 IS NULL AND @old_BC01 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'BC01', @old_BC01, @new_BC01, SYSDATETIME())

IF @new_BC02 <> @old_BC02 OR (@old_BC02 IS NULL AND @new_BC02 IS NOT NULL) OR (@new_BC02 IS NULL AND @old_BC02 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'BC02', @old_BC02, @new_BC02, SYSDATETIME())

IF @new_BC03 <> @old_BC03 OR (@old_BC03 IS NULL AND @new_BC03 IS NOT NULL) OR (@new_BC03 IS NULL AND @old_BC03 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'BC03', @old_BC03, @new_BC03, SYSDATETIME())

IF @new_BC04 <> @old_BC04 OR (@old_BC04 IS NULL AND @new_BC04 IS NOT NULL) OR (@new_BC04 IS NULL AND @old_BC04 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'BC04', @old_BC04, @new_BC04, SYSDATETIME())

IF @new_BC05 <> @old_BC05 OR (@old_BC05 IS NULL AND @new_BC05 IS NOT NULL) OR (@new_BC05 IS NULL AND @old_BC05 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'BC05', @old_BC05, @new_BC05, SYSDATETIME())

IF @new_BC06 <> @old_BC06 OR (@old_BC06 IS NULL AND @new_BC06 IS NOT NULL) OR (@new_BC06 IS NULL AND @old_BC06 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'BC06', @old_BC06, @new_BC06, SYSDATETIME())

IF @new_TN_01 <> @old_TN_01 OR (@old_TN_01 IS NULL AND @new_TN_01 IS NOT NULL) OR (@new_TN_01 IS NULL AND @old_TN_01 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'TN_01', @old_TN_01, @new_TN_01, SYSDATETIME())

IF @new_TN_02 <> @old_TN_02 OR (@old_TN_02 IS NULL AND @new_TN_02 IS NOT NULL) OR (@new_TN_02 IS NULL AND @old_TN_02 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'TN_02', @old_TN_02, @new_TN_02, SYSDATETIME())

IF @new_TN_03 <> @old_TN_03 OR (@old_TN_03 IS NULL AND @new_TN_03 IS NOT NULL) OR (@new_TN_03 IS NULL AND @old_TN_03 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'TN_03', @old_TN_03, @new_TN_03, SYSDATETIME())

IF @new_TN_04 <> @old_TN_04 OR (@old_TN_04 IS NULL AND @new_TN_04 IS NOT NULL) OR (@new_TN_04 IS NULL AND @old_TN_04 IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'TN_04', @old_TN_04, @new_TN_04, SYSDATETIME())

IF @new_DIEMKN <> @old_DIEMKN OR (@old_DIEMKN IS NULL AND @new_DIEMKN IS NOT NULL) OR (@new_DIEMKN IS NULL AND @old_DIEMKN IS NOT NULL)
INSERT INTO THUOCTINH_CHANGE VALUES (@new_CITY_ID, 'DIEMKN', @old_DIEMKN, @new_DIEMKN, SYSDATETIME())
END

DROP TRIGGER THUOCTINH_AUDIT;

-- THU KET QUA TRIGGER
UPDATE THUOCTINH
SET TN_02 = 20
WHERE CITY_ID = 'AC42283'

INSERT INTO THUOCTINH
	(CITY_ID, BC01, BC02, BC03, BC04, BC05, BC06, TN_01, TN_02, TN_03, TN_04, DIEMKN) VALUES
		('AK43258', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000)

SELECT * FROM THUOCTINH
SELECT * FROM THUOCTINH_CHANGE