-- TRIGGER 10
CREATE TRIGGER GIAODICH_AUDIT
ON GIAODICH
AFTER UPDATE, INSERT
AS
DECLARE @new_GIAODICH_ID AS CHAR(7)
DECLARE @new_GOIVP_ID CHAR(7)
DECLARE @new_PLAYER_ID AS INT
DECLARE @new_NGAYGD AS DATETIME

DECLARE @old_GIAODICH_ID AS CHAR(7)
DECLARE @old_GOIVP_ID CHAR(7)
DECLARE @old_PLAYER_ID AS INT
DECLARE @old_NGAYGD AS DATETIME

SELECT @new_GIAODICH_ID = I.GIAODICH_ID FROM INSERTED AS I
SELECT @new_GOIVP_ID = I.GOIVP_ID FROM INSERTED AS I
SELECT @new_PLAYER_ID = I.PLAYER_ID FROM INSERTED AS I
SELECT @new_NGAYGD = I.NGAYGD FROM INSERTED AS I

SELECT @old_GIAODICH_ID = I.GIAODICH_ID FROM DELETED AS I
SELECT @old_GOIVP_ID = I.GOIVP_ID FROM DELETED AS I
SELECT @old_PLAYER_ID = I.PLAYER_ID FROM DELETED AS I
SELECT @old_NGAYGD = I.NGAYGD FROM DELETED AS I

BEGIN
IF @new_GIAODICH_ID <> @old_GIAODICH_ID OR (@old_GIAODICH_ID IS NULL AND @new_GIAODICH_ID IS NOT NULL) OR (@new_GIAODICH_ID IS NULL AND @old_GIAODICH_ID IS NOT NULL)
INSERT INTO GIAODICH_CHANGE VALUES (@new_GIAODICH_ID, 'GIAODICH_ID', @old_GIAODICH_ID, @new_GIAODICH_ID, SYSDATETIME())

IF @new_GOIVP_ID <> @old_GOIVP_ID OR (@old_GOIVP_ID IS NULL AND @new_GOIVP_ID IS NOT NULL) OR (@new_GOIVP_ID IS NULL AND @old_GOIVP_ID IS NOT NULL)
INSERT INTO GIAODICH_CHANGE VALUES (@new_GIAODICH_ID, 'GOIVP_ID', @old_GOIVP_ID, @new_GOIVP_ID, SYSDATETIME())

IF @new_PLAYER_ID <> @old_PLAYER_ID OR (@old_PLAYER_ID IS NULL AND @new_PLAYER_ID IS NOT NULL) OR (@new_PLAYER_ID IS NULL AND @old_PLAYER_ID IS NOT NULL)
INSERT INTO GIAODICH_CHANGE VALUES (@new_GIAODICH_ID, 'PLAYER_ID', CAST(@old_PLAYER_ID AS VARCHAR(6)), CAST(@new_PLAYER_ID AS VARCHAR(6)), SYSDATETIME())

IF @new_NGAYGD <> @old_NGAYGD OR (@old_NGAYGD IS NULL AND @new_NGAYGD IS NOT NULL) OR (@new_NGAYGD IS NULL AND @old_NGAYGD IS NOT NULL)
INSERT INTO GIAODICH_CHANGE VALUES (@new_GIAODICH_ID, 'NGAYGD', CAST(@old_NGAYGD AS varchar(30)), CAST(@new_NGAYGD AS VARCHAR(30)), SYSDATETIME())
END

-- THU KET QUA TRIGGER
UPDATE GIAODICH
SET GOIVP_ID = 'VP_09'
WHERE GIAODICH_ID = 'GD001'

UPDATE GIAODICH
SET PLAYER_ID = 486638, GOIVP_ID = 'VP_08'
WHERE GIAODICH_ID = 'GD001'

INSERT INTO GIAODICH
	(GIAODICH_ID, GOIVP_ID, PLAYER_ID, NGAYGD) VALUES
		('GF091', 'VP_01', 784280, '2021-01-13 22:31:56.000')

SELECT * FROM GIAODICH
SELECT * FROM GIAODICH_CHANGE