-- VIEW 1: SUC CHIEN DAU CUA CAC THANH PHO
CREATE VIEW SUCMANH
AS
SELECT THUOCTINH.CITY_ID, THANHPHO.CITY_NAME,
((BC01 * (SELECT PHONGTHU FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC01')) 
+ (BC02 * (SELECT PHONGTHU FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC02'))
+ (BC03 * (SELECT PHONGTHU FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC03'))
+ (BC04 * (SELECT PHONGTHU FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC04'))
+ (BC05 * (SELECT PHONGTHU FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC05'))
+ (BC06 * (SELECT PHONGTHU FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC06'))) 
* (100 + VANMINH.PHONGTHU)/100
AS PHONGTHU,
((BC01 * (SELECT TANCONG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC01')) 
+ (BC02 * (SELECT TANCONG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC02'))
+ (BC03 * (SELECT TANCONG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC03'))
+ (BC04 * (SELECT TANCONG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC04'))
+ (BC05 * (SELECT TANCONG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC05'))
+ (BC06 * (SELECT TANCONG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC06')))
* (100 + VANMINH.TANCONG)/100
AS TANCONG,
((BC01 * (SELECT XAYDUNG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC01')) 
+ (BC02 * (SELECT XAYDUNG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC02'))
+ (BC03 * (SELECT XAYDUNG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC03'))
+ (BC04 * (SELECT XAYDUNG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC04'))
+ (BC05 * (SELECT XAYDUNG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC05'))
+ (BC06 * (SELECT XAYDUNG FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC06')))
* (100 + VANMINH.XAYDUNG)/100
AS XAYDUNG,
((BC01 * (SELECT HUANLUYEN FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC01')) 
+ (BC02 * (SELECT HUANLUYEN FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC02'))
+ (BC03 * (SELECT HUANLUYEN FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC03'))
+ (BC04 * (SELECT HUANLUYEN FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC04'))
+ (BC05 * (SELECT HUANLUYEN FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC05'))
+ (BC06 * (SELECT HUANLUYEN FROM BINHCHUNG WHERE BINHCHUNG_ID = 'BC06')))
* (100 + VANMINH.HUANLUYEN)/100
AS HUANLUYEN
FROM THUOCTINH
JOIN THANHPHO
ON THANHPHO.CITY_ID = THUOCTINH.CITY_ID
JOIN VANMINH
ON THANHPHO.VANMINH_ID = VANMINH.VANMINH_ID

-- VIEW 2: THONG TIN LIENMINH
CREATE VIEW THONGTINLM
AS
SELECT TV.LIENMINH_ID, LM.LIENMINH_NAME, LM.BOSS_ID,
	   COUNT(TV.PLAYER_ID) AS SOTVIEN,
	   DIEMLIENMINH
FROM LIENMINH AS LM
JOIN THANHVIEN AS TV
ON LM.LIENMINH_ID = TV.LIENMINH_ID
JOIN NGUOICHOI AS NC
ON TV.PLAYER_ID = NC.PLAYER_ID
GROUP BY TV.LIENMINH_ID, LM.LIENMINH_NAME, LM.BOSS_ID, DIEMLIENMINH

-- VIEW 3: 
CREATE VIEW THONGTINNC
AS
SELECT NC.CITY_ID, NICKNAME, DIEMKN, TONGSOTRAN, CHISOTHANG
FROM NGUOICHOI AS NC
JOIN THUOCTINH AS TT
ON NC.CITY_ID = TT.CITY_ID

-- VIEW 4: Số người chơi tạo tài khoản ở các Thế giới
CREATE VIEW SOLUONGACCOUNT
AS
SELECT TG.THEGIOI_ID, TG.THEGIOI_NAME, COUNT(CITY_ID) AS SOLUONG
FROM THEGIOI AS TG
LEFT JOIN THANHPHO AS TP
ON TG.THEGIOI_ID = TP.THEGIOI_ID
GROUP BY TG.THEGIOI_ID, TG.THEGIOI_NAME

-- VIEW 5: BXH 20 NGƯỜI CHƠI CÓ CHỈ SỐ THẮNG CAO NHẤT
CREATE VIEW BXHNGUOICHOI
AS
SELECT TOP(20)
	DENSE_RANK()  OVER(ORDER BY CHISOTHANG DESC, TONGSOTRAN ASC) AS RANKING,
	PLAYER_ID, NICKNAME, CHISOTHANG, TONGSOTRAN
FROM NGUOICHOI 

-- VIEW 6: BXH 10 LIENMINH CO ĐIỂM LIÊN MINH CAO NHẤT
CREATE VIEW BXHLIENMINH
AS
SELECT TOP(10)
	DENSE_RANK() OVER(ORDER BY DIEMLIENMINH DESC, THANHLAP ASC) AS RANKING,
	LIENMINH_ID, LIENMINH_NAME, BOSS_ID, THANHLAP, DIEMLIENMINH
FROM LIENMINH
WHERE THEGIOI_ID = 1